### ISSUE TITLE
SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by ElegantFx** [BlinkTagInc/gtfs-to-html#104]
When trying to start the process with `gtfs-to-html`, this gets returned:
`Error: SQLITE_CANTOPEN: unable to open database file
[  Error: SQLITE_CANTOPEN: unable to open database file
] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}
`

**Comment by brendannee** [comment]
Thanks for opening the issue.

This error means that the `sqlitePath` defined in your config.json isn't valid. Try updating it to a path to a folder that exists with a filename like `/tmp/gtfs` or `~/Downloads/gtfs` (as long as `/tmp`  or `~/Downloads` is a valid  folder.

I just pushed an update to GTFS-to-HTML version 1.4.8 so that a better error message shows up to hopefully help people avoid this issue in the future.
