### ISSUE TITLE
Control how different arrival and departure times (same stop) are shown

### ISSUE THREAD

**Issue by antrim** [BlinkTagInc/gtfs-to-html#14]
Enhancement request: Control how different arrival/depart times are show. e.g. Show in different rows/columns.

**Comment by brendannee** [comment]
@antrim I think the thing to do is check if arrival time is different than departure and if it is show two columns, and label them "Arriving" and "Departing".

Do you think there should be a setting to enable/disable this or should we always split arrival/departure times when they are different?

**Comment by thomastrillium** [comment]
Let's make this easy to enable/disable. In particular I'm thinking about some agencies who use different arrival/departure on the first or last stop_time of a trip, which generally speaking shouldn't be split.

**Comment by brendannee** [comment]
Should it something that can be toggled on a per-timetable or per-stop basis, or just globally?

**Comment by thomastrillium** [comment]
Good question that @antrim should weigh in on before we move forward. My first inclination is to turn this into a feature of timetable_stop_order.txt, so it's fully customizable.

**Comment by antrim** [comment]
> Good question that @antrim should weigh in on before we move forward. My first inclination is to turn this into a feature of timetable_stop_order.txt, so it's fully customizable.

I think that's a good plan. I think we can expect to see some variation in how agencies want to show arrive/depart in their timetables.

But, since timetable_stop_order.txt is an optional input for GTFS-to-HTML, then there also needs to be a global default.

**Comment by thomastrillium** [comment]
- i think the names are good. long but very clear.
- default value of 'differentArriveDepart' should be false i imagine
- route 44 has a hold over at the Santa Rosa Transit Mall (which currently we're not visualizing on the html)

**Comment by brendannee** [comment]
I pushed an update that adds this feature.

* Instead of needing a new field to control if you want different arrival and departure times to show up, you can just include the same stop twice in a row in `timetable_stop_order.text`. When that happens, a different arrival and departure row will be shown.

Here is an example of the output for Route 44 of Sonoma Transit with "Santa Rosa Transit mall" showing up twice:

<img width="975" alt="screen shot 2017-03-14 at 5 21 25 am" src="https://cloud.githubusercontent.com/assets/96217/23877665/59e0c0fe-087e-11e7-9818-b0ba5b367a7d.png">

Here is an example timetable_stop_order.txt file for Sonoma Transit with route 44 (timetable_id 54, 55, 56, 57) that has the "Santa Rosa Transit mall" stop listed twice in a row. [timetable_stop_order.txt](https://github.com/brendannee/gtfs-to-html/files/839829/timetable_stop_order.txt)

Let me know what you think of this solution.

**Comment by brendannee** [comment]
Closing this issue as the solution listed above enables different arrival and departure times to be shown.
