### ISSUE TITLE
Not finding the html file

### ISSUE THREAD

**Issue by CookedTomato** [BlinkTagInc/gtfs-to-html#142]
Hi!

Am I dumb or what, but I physically cannot find the html file generated by gtfs-to-html.

Thanks!

**Comment by brendannee** [comment]
No! I'd like to make it easier to find.

If you installed globally via NPM, then the HTML will be in a folder called `html` in whatever directory you ran the `gtfs-to-html` script in.

Also, the output of the `gtfs-to-html` script should print the directory that the files were written to:
<img width="771" alt="Screen Shot 2022-04-11 at 9 02 17 AM" src="https://user-images.githubusercontent.com/96217/162782637-b4f6c529-e9b4-43e8-99c5-1b5d65942e80.png">

Let me know if that helps, and also where you think in the documentation we should highlight this gtfstohtml.com

**Comment by CookedTomato** [comment]
![image](https://user-images.githubusercontent.com/70381789/162784433-19dca627-ed83-4202-a609-542cdf63baf1.png)
This is what it shows me and for some reason the file isn't a folder called html.
Thanks for you quick response!

**Comment by CookedTomato** [comment]
That didn't work

**Comment by brendannee** [comment]
I'll try out running this with your GTFS file and see where the issues are and let you know.

**Comment by CookedTomato** [comment]
Thanks!

**Comment by brendannee** [comment]
Usually, a timetables.txt file isn't strictly required - if missing `gtfs-to-html` will just generate timetables for every single route/direction/calendar.

However, since the GTFS file you are using is fairly large, it fails when trying to do this (runs out of memory), so including a timetables.txt file helps to narrow down what is needed.

Let me know if you end up using this and would like your agency listed here https://gtfstohtml.com/docs/current-usage
