### ISSUE TITLE
Bus locations not showing up on map

### ISSUE THREAD

**Issue by alter-x5** [BlinkTagInc/gtfs-to-html#177]
Hello!

The vehicle locations does not seem to be showing up on the map.

The following is the config.json file.
[config.json](https://github.com/user-attachments/files/17838313/config.json)

I'm using the latest version of gtfs-to-html.

**Comment by brendannee** [comment]
Thanks for reporting this issue and sharing your config.

I tried generating timetables and see that the GTFS-Realtime URLs do not include CORS headers in their response.

https://lbtgtfs.lbtransit.com/TMGTFSRealTimeWebService/Vehicle/VehiclePositions.pb https://lbtgtfs.lbtransit.com/TMGTFSRealTimeWebService/TripUpdate/TripUpdates.pb

This means that any frontend code not running on lbtgtfs.lbtransit.com is unable to fetch these endpoints due to cross-origin browser restrictions.

There are two options:

* Add CORS headers to these endpoints
* Run a small proxy service to expose these endpoints with CORS headers. 

I have an example repo of a serverless proxy service to add CORS headers to GTFS-Realtime feeds I could provide if that would be useful.

**Comment by alter-x5** [comment]
Thank you for your helpful response!
