### ISSUE TITLE
Timetable diff tool

### ISSUE THREAD

**Issue by antrim** [BlinkTagInc/gtfs-to-html#24]
Open thread for feature: feature to compare differences in timetables in service updates.

(Concept borrowed from TimeTable Publisher: http://www.transitwiki.org/TransitWiki/index.php?title=Timetable_Publisher)

**Comment by brendannee** [comment]
In order to do a diff, we'd need to generate schedules for two different GTFS files. 

Do you imagine having a new command like:

`./bin/gtfs-to-html-diff old-gtfs-file.zip new-gtfs-file.zip`

that takes two GTFS files, generates the HTML timetables for each and then shows a diff?

**Comment by thomastrillium** [comment]
instead of comparing to a GTFS file, would it be feasible to compare to an output? (a folder of html files)

**Comment by brendannee** [comment]
Yes, it could do that. I could make it a command line utility so you run

./bin/gtfs-to-html-diff path/to/old/schedule/html/folder path/to/new/schedule/html/folder

Does that seem acceptable?

**Comment by thomastrillium** [comment]
@antrim or @nomeq do you have opinions on which way we go here? My thought is that if there is minor post processing, checking against the html provides a dif against what is actually live on the site instead of was in the GTFS.

But that might be the wrong way to think of this tool.

**Comment by NomeQ** [comment]
I think that comparing HTML could be nice for lightweight use, but I think it's exactly that post-processing that could muck things up, and make the diff sensitive to meaningless html changes, rather than only capturing data changes.

**Comment by antrim** [comment]
There might also be an issue introduced if an updated version GTFS-to-HTML changes its output style slightly. For that reason, it might be useful to have the same software generate and diff the HTML all at the same time. I'd suggest that as the default.

I do like the idea of an override to diff to a previously-generated HTML file.

**Comment by brendannee** [comment]
I was able to generate a nice HTML diff using two tools: diff and diff2html.

I can document the steps to how to do this in the readme if this process seems like an acceptable option for diffing.

* First generate two folders of output you'd like to diff. I changed the `noServiceSymbol` in config.json to make some simple changes between the two

Then, install diff2html

    npm install -g diff2html-cli

With this, you can use the `diff` tool and pipe the output to diff2html

    diff -bur html/countyconnection html/countyconnection-old |  diff2html -i stdin

In the above example, my two folders I want to compare are `html/countyconnection` and `html/countyconnection-old`.

This command generates a nicely formatted HTML diff and opens in your browser. Since the HTML output of `gtfs-to-html` is minified, its nice to have a diff visualization that highlights what changed on each line.

<img width="1271" alt="screen shot 2017-04-26 at 5 37 38 pm" src="https://cloud.githubusercontent.com/assets/96217/25462915/1b421ece-2aa7-11e7-876a-a290dd9fc206.png">

Do you think this process is sufficient as a timetable diff tool?

* I'll add an option to not minify the HTML so that will make diffing the output easier to parse
* I can document the above steps in the GTFS-to-HTML readme.
* If you think its worth it, I could wrap this into a command `gtfs-to-html-diff` that takes two folders and does the diff. Let me know.

**Comment by brendannee** [comment]
I added an option to gtfs-to-html to beautify the output - see the most recent release.

This will make diffing easier and manually making any changes to the output a bit easier to manage.

**Comment by brendannee** [comment]
@antrim @NomeQ Do you think I should add the diffing steps above to the README.md for GTFS-to-HTML or do you think this feature needs to be baked into the code?

**Comment by antrim** [comment]
I don’t have an opinion on this.

**Comment by brendannee** [comment]
I added this info to the project readme, closing this issue.
