### ISSUE TITLE
partial trip displays broken stop_times

### ISSUE THREAD

**Issue by thomastrillium** [BlinkTagInc/gtfs-to-html#30]
I believe I've seen this before, not sure if an issue has addressed this before.

Problem:
- Loop route begins and ends with the same stop
- Most trips during day have full stop order (with two iterations of the first/last stop)
- however, some trips during the day start halfway through the stop order
- GTFS-to-HTML prints such trips with the trip END time assigned to the first row of the trip, no stop_times printed for all stops in the middle of the trip, and the trip end time again assigned to the repeated last stop_time

Example:
See this GTFS, and resulting in timetables:
[juneau_html_timetables.zip](https://github.com/brendannee/gtfs-to-html/files/839717/juneau_html_timetables.zip)

Route 5 timetable shows problem as described above, with 7:27 printed for  first and last stop_time of first trip (the only partial trip for that route).

**Comment by brendannee** [comment]
I pushed some updates today that may solve this issue.

Default to using longest trip to get stops https://github.com/BlinkTagInc/gtfs-to-html/commit/db638541d918b62b4013807e539320a04e77e87b
Use stop in common for sorting trips https://github.com/BlinkTagInc/gtfs-to-html/commit/0a7015b06ff0a9243cb5580117ee730360b978ca

These may have resolved this issue - can you try out the latest code on the master branch and reopen this issue if it is still a problem?

**Comment by hkvlhm** [comment]
This issue persists (I'm using version 0.8.0)

**Comment by brendannee** [comment]
I identified the issue.

In order to resolve it, I had to adjust how the core of GTFS-to-HTML determines the stop in common between all trips (when its a loop, ignore the first stop) and also how it sorts stoptimes into stops.

I was able to make it work to output Juneau Route 5 correctly, however this change will impact how all schedules are created. I pushed it to a branch for us to try out:

https://github.com/BlinkTagInc/gtfs-to-html/tree/stoporder

Here is the commit with the change in logic: https://github.com/BlinkTagInc/gtfs-to-html/commit/a799d1d898c9c75f346d379063d1fe0fec2d5590

Can you run the code on this branch against a few other agencies and let me know if there are unintended consequences or routes that break? If not, then I'll merge it into master.

**Comment by brendannee** [comment]
I tested out this branch and it seems to work as expected on all routes and agencies I tested it with.

I merged it into master and am closing this issue - please let me know if you see any issues.
