### ISSUE TITLE
Support for frequency-based schedules (frequencies.txt)?

### ISSUE THREAD

**Issue by nselikoff** [BlinkTagInc/gtfs-to-html#40]
Hello! This is an awesome and very useful project, thank you for sharing it and maintaining it.

From what I can tell, there is not currently support for frequency-based schedules. Is that correct?

**Comment by brendannee** [comment]
You are correct - there isn't support for this yet. Do you have an example GTFS file for an agency that uses frequencies.txt on some routes?

**Comment by nselikoff** [comment]
Sure, here's one: https://transitfeeds.com/p/san-diego-mts/195/latest/route/AIR

https://transitfeeds.com/p/san-diego-mts/195/latest/download
https://transitfeeds.com/p/san-diego-mts/195/latest/file/frequencies.txt

**Comment by brendannee** [comment]
Great - I pushed an udpate that now displays info about a routes frequency if there is info in frequencies.txt

Give it a try for the San Diego GTFS and let me know what you think.

**Comment by nselikoff** [comment]
Hey @brendannee thanks for getting this started. So for frequency based schedules, the stop times need to be calculated somewhat differently:

"Actual stop times are ignored for trips referenced by frequencies.txt; only travel time intervals between stops are significant for frequency-based trips. For clarity/human readability, it is recommended that the first stop time of a trip referenced in frequencies.txt should begin at 00:00:00 (first arrival_time value of 00:00:00)."

(From GTFS Best Practices: http://gtfs.org/best-practices/#frequencies)

E.g. it should be `start_time` from frequencies.txt + `arrival_time` from stop_times.txt

I would suggest that for horizontal and vertical timetable layouts, all rows/columns should be extrapolated out. With this example data, that will show that the trolley leaves from Palm Street at 12:00am, 12:15am, 12:30am, 12:45am, etc. 

And for the hourly layout, it would show
Palm Street | :00 :15 :30 :45
Terminal 1 | :10 :25 :40 :55
etc

What do you think?

**Comment by brendannee** [comment]
Great idea.

I pushed updates to the master branch to better handle the formatting. Now, vertical timetables with frequencies list out all times and hourly shows times for a 60 minute period.

Try out the master branch and let me know what you think.

**Comment by nselikoff** [comment]
Looking great, thank you for working on this. Couple of things:

1. Regarding the "Trip times shown below are an example only." text: maybe only show that if `exact_times` is 0 or empty. If it's 1, don't show that text. (Ref: https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#frequenciestxt)
	
2. For consistency, it would be great if hovering over the stops on an hourly timetable highlighted those stops on the map, like vertical and horizontal.

3. On the hourly layout, I'm wondering if the "minutes after the hour" values should be sorted individually within each cell, e.g. instead of `:53, :08, :23, :38`, it would be `:08, :23, :38, :53` regardless of which came first in the 60 minute period.

I haven't tried it yet, but would the hourly layout also show times for a 60 minute period on a non-frequency based route?

**Comment by brendannee** [comment]
Great suggestions. 

* The current master branch now has code that only shows the frequency warning if `exact_times` isn't 1.

* The map effect where stops are highlighted on hover now works for hourly timetables.

* For the hourly layout, times are now sorted so that for the first stop they are in numerical order like `:08, :23, :38, :53`. The order stays the same for each trip, so you can still see how long it takes to go between stops. See the last stop of this route 
<img width="804" alt="screen shot 2017-08-20 at 1 36 37 am" src="https://user-images.githubusercontent.com/96217/29493336-a659590e-8548-11e7-9bec-940aa2cb2bd1.png"> - the times are not in order so that they line up with the times from the first stop.

* On the hourly layout, it will now show times for a 60 minute period for non-frequency based routes as well.

Let me know what you think and if I'm missing anything.

**Comment by nselikoff** [comment]
I think it looks great! Nothing missing that I can see. 👍

**Comment by brendannee** [comment]
Great - I published this as version 0.12.2
