### ISSUE TITLE
Custom templates will never use `overview_full.pug`

### ISSUE THREAD

**Issue by nselikoff** [BlinkTagInc/gtfs-to-html#42]
When specifying a custom template, the logic in `getOverviewTemplateFile` will always use `overview.pug` (making it so the generated HTML doesn't include the head etc).

See https://github.com/BlinkTagInc/gtfs-to-html/blob/master/lib/file-utils.js#L65

**Comment by brendannee** [comment]
Great catch.

I pushed an update to the master branch so that the `templatePath` config variable should specify a folder containing templates. That folder should have `timetablepage.pug`, `timetablepage_full.pug`,  `overview.pug`, and `overview_full.pug`. This way, the `noHead` config option will work for both timetablepage and overview files.

Check out the master branch and let me know what you think.

**Comment by nselikoff** [comment]
Works great, thanks
