### ISSUE TITLE
direction_id=null no longer supported?

### ISSUE THREAD

**Issue by evantrillium** [BlinkTagInc/gtfs-to-html#73]
cc: @ed-g @anniekfifer 

Today when running GTFS-to-HTML on http://oregon-gtfs.com/gtfs_data/hoodriver-or-us/hoodriver-or-us.zip I was presented with the following error I have not encountered before

hoodriver: Generating HTML timetables [------------------] 0/18
Error: TypeError: Cannot read property 'direction_id' of undefined
TypeError: Cannot read property 'direction_id' of undefined
    at convertRouteToTimetablePage (/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js:348:29)
    at Object.exports.getFormattedTimetablePage (/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js:1009:27)
    at process._tickCallback (internal/process/next_tick.js:178:7)

I went into trips.txt and modified it by adding '0' as a value under any trip with direction_id=null (allowed by spec), which appeared to resolve the issue.

I know I pulled new template files last week - was this changed in the templates?

**Comment by evantrillium** [comment]
config file attached. Most recent version of gtfs-to-html. Still seeing this error
[config.txt](https://github.com/BlinkTagInc/gtfs-to-html/files/3648309/config.txt)

**Comment by brendannee** [comment]
Thanks for sending the config file.

I just tried gtfs-to-html version 0.17.10 with the config you sent and got no errors, 24 timetables.

Reviewing the error message you posted above, I suspect you may not be on the latest version of gtfs-to-html because `/usr/local/lib/node_modules/gtfs-to-html/lib/utils.js` line 348 is blank in the latest version https://github.com/BlinkTagInc/gtfs-to-html/blob/master/lib/utils.js#L348 Try grabbing the latest code and see what you get.

**Comment by evantrillium** [comment]
ah - I was missing a part of the update process (I only sort-of updated, it seems!)

Working now - thank you!
